const text = [
  `Taj Mahal, also spelled Tadj Mahall, mausoleum complex in Agra, western Uttar Pradesh state, northern India. The Taj Mahal was built by the Mughal emperor Shah Jahān (reigned 1628–58) to immortalize his wife Mumtaz Mahal (“Chosen One of the Palace”), who died in childbirth in 1631, having been the emperor’s inseparable companion since their marriage in 1612. India’s most famous and widely recognized building, it is situated in the eastern part of the city on the southern (right) bank of the Yamuna (Jumna) River. Agra Fort (Red Fort), also on the right bank of the Yamuna, is about 1 mile (1.6 km) west of the Taj Mahal.`,
  `In its harmonious proportions and its fluid incorporation of decorative elements, the Taj Mahal is distinguished as the finest example of Mughal architecture, a blend of Indian, Persian, and Islamic styles. Other attractions include twin mosque buildings (placed symmetrically on either side of the mausoleum), lovely gardens, and a museum. One of the most beautiful structural compositions in the world, the Taj Mahal is also one of the world’s most iconic monuments, visited by millions of tourists each year. The complex was designated a UNESCO World Heritage site in 1983.`,
  `The plans for the complex have been attributed to various architects of the period, though the chief architect was probably Ustad Aḥmad Lahawrī, an Indian of Persian descent. The five principal elements of the complex—main gateway, garden, mosque, jawāb (literally “answer”; a building mirroring the mosque), and mausoleum (including its four minarets)—were conceived and designed as a unified entity according to the tenets of Mughal building practice, which allowed no subsequent addition or alteration. Building commenced about 1632. More than 20,000 workers were employed from India, Persia, the Ottoman Empire, and Europe to complete the mausoleum itself by about 1638–39; the adjunct buildings were finished by 1643, and decoration work continued until at least 1647. In total, construction of the 42-acre (17-hectare) complex spanned 22 years.`,
  `Resting in the middle of a wide plinth 23 feet (7 metres) high, the mausoleum proper is of white marble that reflects hues according to the intensity of sunlight or moonlight. It has four nearly identical facades, each with a wide central arch rising to 108 feet (33 metres) at its apex and chamfered (slanted) corners incorporating smaller arches. The majestic central dome, which reaches a height of 240 feet (73 metres) at the tip of its finial, is surrounded by four lesser domes. The acoustics inside the main dome cause the single note of a flute to reverberate five times. The interior of the mausoleum is organized around an octagonal marble chamber ornamented with low-relief carvings and semiprecious stones (pietra dura). Therein are the cenotaphs of Mumtaz Mahal and Shah Jahān. Those false tombs are enclosed by a finely wrought filigree marble screen. Beneath the tombs, at garden level, lie the true sarcophagi. Standing gracefully apart from the central building, at each of the four corners of the square plinth, are elegant minarets.`,
  `Flanking the mausoleum near the northwestern and northeastern edges of the garden, respectively, are two symmetrically identical buildings—the mosque, which faces east, and its jawāb, which faces west and provides aesthetic balance. Built of red Sikri sandstone with marble-necked domes and architraves, they contrast in both colour and texture with the mausoleum’s white marble.
  The garden is set out along classical Mughal lines—a square quartered by long watercourses (pools)—with walking paths, fountains, and ornamental trees. Enclosed by the walls and structures of the complex, it provides a striking approach to the mausoleum, which can be seen reflected in the garden’s central pools.`,
  `The southern end of the complex is graced by a wide red sandstone gateway with a recessed central arch two stories high. White marble paneling around the arch is inlaid with black Qurʾānic lettering and floral designs. The main arch is flanked by two pairs of smaller arches. Crowning the northern and southern facades of the gateway are matching rows of white chattris (chhattris; cupola-like structures), 11 to each facade, accompanied by thin ornamental minarets that rise to some 98 feet (30 metres). At the four corners of the structure are octagonal towers capped with larger chattris.`,
  `Two notable decorative features are repeated throughout the complex: pietra dura and Arabic calligraphy. As embodied in the Mughal craft, pietra dura (Italian: “hard stone”) incorporates the inlay of semiprecious stones of various colours, including lapis lazuli, jade, crystal, turquoise, and amethyst, in highly formalized and intertwining geometric and floral designs. The colours serve to moderate the dazzling expanse of the white Makrana marble. Under the direction of Amānat Khan al-Shīrāzī, verses from the Qurʾān were inscribed across numerous sections of the Taj Mahal in calligraphy, central to Islamic artistic tradition. One of the inscriptions in the sandstone gateway is known as Daybreak (89:28–30) and invites the faithful to enter paradise. Calligraphy also encircles the soaring arched entrances to the`,
  `Over the centuries the Taj Mahal has been subject to neglect and decay. A major restoration was carried out at the beginning of the 20th century under the direction of Lord Curzon, then the British viceroy of India. More recently, air pollution caused by emissions from foundries and other nearby factories and exhaust from motor vehicles has damaged the mausoleum, notably its marble facade. A number of measures have been taken to reduce the threat to the monument, among them the closing of some foundries and the installation of pollution-control equipment at others, the creation of a parkland buffer zone around the complex, and`,
  `Born Arjumand Banu, she was a member of a family that came to command the inner court of the Mughal dynasty in the 17th century. Her family’s high status was secured when her aunt Mehr al-Nesāʾ married Shah Jahān’s father, Jahāngīr, in 1611 (and thereafter she was known as Nūr Jahān). Arjumand’s grandfather Mirzā Ghiyās Beg (known also as Iʿtimād al-Dawlah, “Pillar of the State”), who had entered the royal court during the reign of`,
  `Arjumand was betrothed to Prince Khurram (the pre-regnal name of Shah Jahān) in 1607, but it was not until 1612—the date chosen by the court astrologers—that they were permitted to marry. In the meantime, he had taken another wife, and Arjumand thus became his second wife. She bore 14 children during their marriage, seven of whom survived to adulthood. Their third son was Aurangzeb, the last great Mughal emperor (1658–1707).`,
  `Shah Jahān acceded the throne in 1628 and conferred on Arjumand the title of Mumtāz Maḥall (“Chosen One of the Palace”). Though she did not assert authority to the extent her aunt had done, she used her position to promote humanitarian programs for the needy. In 1631, though pregnant, she accompanied Shah Jahān on a military campaign in the Deccan. While in Burhanpur, she gave birth to their 14th child and soon after died from hemorrhaging.`,
];

export default text;
